"""Tests for sandbox Operations event generators.

Validates intel update and ops alert events generated by the sandbox
activity generator for the Operations station.
"""
from __future__ import annotations

import pytest

import server.game_loop_sandbox as glsb
from server.models.world import World, spawn_enemy


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _make_world() -> World:
    w = World()
    w.ship.x = 50_000.0
    w.ship.y = 50_000.0
    return w


@pytest.fixture(autouse=True)
def _reset():
    glsb.reset(active=False)
    yield
    glsb.reset(active=False)


# ===========================================================================
# Intel Update
# ===========================================================================


class TestSandboxIntelUpdate:
    def test_intel_timer_exists(self) -> None:
        glsb.reset(active=True)
        assert "sandbox_intel_update" in glsb._timers

    def test_intel_update_with_enemies(self) -> None:
        """When enemies exist, intel update contains target data."""
        glsb.reset(active=True)
        glsb._timers["sandbox_intel_update"] = 0.05
        world = _make_world()
        world.enemies.append(spawn_enemy("scout", 55000.0, 55000.0, "enemy_1"))
        events = glsb.tick(world, 0.1)
        intels = [e for e in events if e["type"] == "sandbox_intel_update"]
        assert len(intels) == 1
        assert intels[0]["enemy_id"] == "enemy_1"
        assessment = intels[0]["assessment"]
        assert "threat_level" in assessment
        assert "bearing" in assessment
        assert "range" in assessment
        assert "recommendation" in assessment

    def test_intel_update_no_enemies(self) -> None:
        """When no enemies, intel update is sector status."""
        glsb.reset(active=True)
        glsb._timers["sandbox_intel_update"] = 0.05
        world = _make_world()
        events = glsb.tick(world, 0.1)
        intels = [e for e in events if e["type"] == "sandbox_intel_update"]
        assert len(intels) == 1
        assert intels[0]["enemy_id"] is None
        assert "sector_status" in intels[0]["assessment"]

    def test_intel_interval_constant(self) -> None:
        assert glsb.SANDBOX_INTEL_UPDATE_INTERVAL == (60.0, 90.0)

    def test_intel_timer_resets(self) -> None:
        glsb.reset(active=True)
        glsb._timers["sandbox_intel_update"] = 0.05
        world = _make_world()
        glsb.tick(world, 0.1)
        assert glsb._timers["sandbox_intel_update"] > 10.0


# ===========================================================================
# Ops Alert
# ===========================================================================


class TestSandboxOpsAlert:
    def test_ops_alert_timer_exists(self) -> None:
        glsb.reset(active=True)
        assert "sandbox_ops_alert" in glsb._timers

    def test_ops_alert_fires(self) -> None:
        glsb.reset(active=True)
        glsb._timers["sandbox_ops_alert"] = 0.05
        world = _make_world()
        events = glsb.tick(world, 0.1)
        alerts = [e for e in events if e["type"] == "sandbox_ops_alert"]
        assert len(alerts) == 1
        assert "alert" in alerts[0]
        assert "severity" in alerts[0]
        assert alerts[0]["severity"] in ("info", "warning", "critical")
        assert "source" in alerts[0]

    def test_ops_alert_reads_game_state(self) -> None:
        """When ship has enemies, should get tactical alerts."""
        glsb.reset(active=True)
        world = _make_world()
        world.enemies.append(spawn_enemy("scout", 55000.0, 55000.0, "e1"))
        world.enemies.append(spawn_enemy("cruiser", 60000.0, 55000.0, "e2"))
        # Run many times to get a tactical alert.
        alerts_seen: list[str] = []
        for _ in range(50):
            glsb._timers["sandbox_ops_alert"] = 0.05
            events = glsb.tick(world, 0.1)
            for e in events:
                if e["type"] == "sandbox_ops_alert":
                    alerts_seen.append(e["alert"])
        assert len(alerts_seen) > 0

    def test_ops_alert_interval_constant(self) -> None:
        assert glsb.SANDBOX_OPS_ALERT_INTERVAL == (90.0, 120.0)

    def test_ops_alert_difficulty_scaling(self) -> None:
        """Timer interval should scale with difficulty multiplier."""
        class EasyDifficulty:
            event_interval_multiplier = 1.5
            boarding_frequency_multiplier = 1.0

        glsb.reset(active=True)
        glsb._timers["sandbox_ops_alert"] = 0.05
        world = _make_world()
        glsb.tick(world, 0.1, difficulty=EasyDifficulty())
        # Timer should be scaled by 1.5×.
        assert glsb._timers["sandbox_ops_alert"] >= 90.0 * 1.5
